services:
  nextjs:
    container_name: nextjs-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - $NEXTJS_EXTERNAL_PORT:$NEXTJS_INTERNAL_PORT
    environment:
      - PORT=$NEXTJS_INTERNAL_PORT
    networks:
      - next-network

volumes:
  node_modules:

networks:
  next-network:
    driver: bridge
