name: Auto Close Issue

on:
  pull_request:
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

run-name: Auto Close Issue

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-pull-request-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  auto-close:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, vars.CLICKUP_PULL_REQUEST_PREFIX) && github.event.pull_request.merged == true
    steps:
      - name: Extract ClickUp Task ID
        id: pull_request_task_id
        run: echo "TASK_ID=$(echo ${{ github.event.pull_request.title }} | grep -oP '(?<=\[CU-)[A-Za-z0-9]+(?=\])')" >> "$GITHUB_OUTPUT"

      - name: Close Automated Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            const task_id = "${{ steps.pull_request_task_id.outputs.TASK_ID }}";

            const issue = await github.rest.search.issuesAndPullRequests({
                q: `repo:${{ github.repository }} in:title ${task_id} is:issue is:open`
            });

            if (issue.data.total_count === 0) {
                console.log(`No issue found for task ${task_id}`);
                return;
            }

            const issue_number = issue.data.items[0].number;

            await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: `This issue was automatically closed by PR #${{ github.event.pull_request.number }}.`
            });

            await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                state: 'closed'
            });
