name: 🐳 Docker Build & Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  docker-build-test:
    name: 🐳 Build & Test Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Production Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: false
          tags: next-starter:prod
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Development Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: development
          push: false
          tags: next-starter:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Comment on PR if Docker tests fail
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Docker build or test failed.** Please check the logs and fix the issues.\n\n**Failed checks:**\n- Docker image build\n- Container health tests'
            })
