name: 🐳 Docker Build & Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  docker-build:
    name: 🐳 Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create environment files
        run: |
          echo "NODE_ENV=production" > .env.prod
          echo "NEXTJS_EXTERNAL_PORT=3000" >> .env.prod
          echo "NEXTJS_INTERNAL_PORT=3000" >> .env.prod

          echo "NODE_ENV=development" > .env.dev
          echo "NEXTJS_EXTERNAL_PORT=3000" >> .env.dev
          echo "NEXTJS_INTERNAL_PORT=3000" >> .env.dev

      - name: Build Production Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: false
          tags: next-starter:prod
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Development Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          push: false
          tags: next-starter:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker-test:
    name: 🧪 Test Docker Images
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create environment files
        run: |
          echo "NODE_ENV=production" > .env.prod
          echo "NEXTJS_EXTERNAL_PORT=3000" >> .env.prod
          echo "NEXTJS_INTERNAL_PORT=3000" >> .env.prod

      - name: Test Production Container
        run: |
          docker run -d --name test-prod -p 3000:3000 next-starter:prod
          sleep 30

          # Test health endpoint
          curl -f http://localhost:3000/api/health || exit 1

          # Test main page
          curl -f http://localhost:3000 || exit 1

          docker stop test-prod
          docker rm test-prod

      - name: Test Development Container
        run: |
          docker run -d --name test-dev -p 3001:3000 next-starter:dev
          sleep 30

          # Test that dev server is running
          curl -f http://localhost:3001 || exit 1

          docker stop test-dev
          docker rm test-dev

      - name: Comment on PR if Docker tests fail
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Docker build or test failed.** Please check the logs and fix the issues.\n\n**Failed checks:**\n- Docker image build\n- Container health tests'
            })
